### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-client-python#1]
- [ ] Set sane default connection timeouts
- [ ] Limit maxrows / add sampling by default (+ warning)
- [ ] Ability to query at specific block
- [ ] Search API
- [ ] Push data API
- [ ] CI actions
- [ ] Async interface
- [ ] Generate API documentation and embed into docs portal
- [ ] Consider connecting to ODF HTTP and discovering engine URLs instead of connecting directly
